#!/bin/ash


# Configuration
# -------------

EXEC="wpa-service"
INTRO="An init script for wpad and wpa_cli"
ROOTDIR=/extdisks/sda1/data
config_file="/etc/wpa_supplicant.conf"


# Usage
# -----

usage() {
	echo "Usage: $EXEC start|status|stop"
	echo "Try '$EXEC --help' for more information."
	
	return 0
}


# Help
# ----

help() {
	echo -e "NAME"
	echo -e "\t$EXEC - $INTRO"
	echo -e ""
	echo -e "SYNOPSIS"
	echo -e "\t$EXEC start|status|stop"
        echo -e "\t$EXEC --help"
	echo -e ""
	echo -e "DESCRIPTION"
        echo -e "\tstart\t\t start wpad"
	echo -e "\tstatus\t\t check the status of wpa_cli"
        echo -e "\tstop\t\t stop wpad"
        echo -e "\t--help\t\t display this help"
        
        return 0
}


# Start
# -----

start() {
	$ROOTDIR/usr/sbin/wpa_supplicant \
	-i eth0.2 -D wired -c $config_file -B
	
	return 0
}


# Status
# ------

status() {
	$ROOTDIR/usr/sbin/wpa_cli status
	
	return 0
}


# Stop
# ----

stop() {
	$ROOTDIR/usr/sbin/wpa_cli logoff
	$ROOTDIR/usr/sbin/wpa_cli terminate
	
	return 0
}


# Main
# ----

# check parameters
if [[ "$1" == "--help" ]]; then
	help
	exit 0
elif [[ "$1" != "start" ]] && [[ "$1" != "status" ]] \
	&& [[ "$1" != "stop" ]]; then
	usage
	exit 0
fi

# start, status, and stop
if [[ "$1" == "start" ]]; then
	start
elif [[ "$1" == "status" ]]; then
	status
elif [[ "$1" == "stop" ]]; then
	stop
fi
